### ISSUE TITLE
buttonとeditorについて

### ISSUE THREAD

**Issue by jucky154** [nextzlog/zylo#1]
以下を実行しているのですが、どのボタンやキー（A,Bなど/上の1,2,やCQ）を押しても何も出ません。
zlaunchの際のCQ!は出ていますし、集中モードではないことも確認しています
[talker.txt](https://github.com/nextzlog/zylo/files/6646414/talker.txt)

**Comment by JG1VPP** [comment]
ZyLOはデフォルトではどのボタンのイベントも拾いません。
イベントを拾うためには`zylo.HookButton`という関数を呼び出します。

```
zylo.HookButton("CWPlayButton")
```

この関数を呼び出すと、それ以後、`CWPlayButton`が押されるたびに`zbutton`関数が呼び出されます。

具体的なボタンの名前は、zLogのdfmファイルを参照してください。
https://github.com/jr8ppg/zLog/blob/master/zlog/main.dfm

dfmファイルにはUIに並ぶオブジェクトが列挙されています。

```
object 名前: 型
  // 入れ子の内側
end
```

現状では、main.dfmに含まれる全てのTButtonまたはTMenuItemに対応しています。

**Comment by jucky154** [comment]
ありがとうございます

**Comment by JG1VPP** [comment]
同様です。こちらはTEditに対応しています。
