### ISSUE TITLE
go.modについて

### ISSUE THREAD

**Issue by jucky154** [nextzlog/zylo#2]
zbuildで自動的に出てくるgo.modは
github.com/nextzlog/zylo v0.1.2
ですが、古いバージョンなので
github.com/nextzlog/zylo v0.0.0-20210521184630-fc41d0be65b6
を使っているのですが、
自分のコールサインを知るためにzlog.iniを読み書きしたいので最新版を使いたいのですが、ここのversionの書き方がわかりません。
ご教示いただけると幸いです。

**Comment by JG1VPP** [comment]
ZyLOのパッケージを削除してください。
GOPATHという環境変数があれば、GOPATHが指すディレクトリ以下にパッケージがインストールされていると思います。

**Comment by jucky154** [comment]
GOPATHのあるところのsrcなどの中にあったgithub.com/nextzlogを全て削除したのですがgithub.com/nextzlog/zylo v0.1.2が連れてこられます。

**Comment by JG1VPP** [comment]
以下を試してください。

```
go clean -modcache
go clean -cache
```

**Comment by jucky154** [comment]
同様です。
v0.1.2にがダウンロードされ、
asset.goからundefined : zylo.InsertQSOなどが出て、ビルドしたい方からqso.Score undefinedなどと出ます。

**Comment by JG1VPP** [comment]
```
go env GOCACHE
```

で表示されるディレクトリを削除し、そのままOSを再起動してもらえますか？

**Comment by jucky154** [comment]
削除し再起動した場合は
[first.txt](https://github.com/nextzlog/zylo/files/6647481/first.txt)
１回目は上のようなエラーを吐きました。
よって、再度行うと
[second.txt](https://github.com/nextzlog/zylo/files/6647486/second.txt)
これまでと同様のエラーを吐きました

**Comment by JG1VPP** [comment]
インターネット接続の問題ではないでしょうか？
ブラウザで https://proxy.golang.org/github.com/faiface/beep/wav/@v/list にアクセスできますか？

**Comment by jucky154** [comment]
https://github.com/nextzlog/zylo/issues/2#issuecomment-860526372
https://github.com/nextzlog/zylo/issues/2#issuecomment-860557383
を実行し、インターネット接続を確認してから再度実行いたしました。
v0.1.2にがダウンロードされます。
windowsからだとv0.1.2がダウンロードされるんですかね？
私としてはversionのみしれれば問題ありません。

**Comment by JG1VPP** [comment]
まず、v0.1.2というのは存在しません。従って、存在しないバージョンをダウンロードしています。

**Comment by JG1VPP** [comment]
go get github.com/nextzlog/zylo@v0.0.0 ではどうですか？

**Comment by jucky154** [comment]
go get : github.com/nextzlog/zylo@v0.0.0 : invalid version : unknown revision v0.0.0
です。　git bashを用いているのがまずいのかもしれないので、powershellを使ってみます

**Comment by jucky154** [comment]
powershellの場合は 
go get : can't request version "v0.0.0" of the main module (github.com/nextzlog/zylo)
となりました。

**Comment by JG1VPP** [comment]
go get github.com/nextzlog/v0.0.0-20210612174204-27dece334bd4
ではどうですか？

**Comment by JG1VPP** [comment]
go get github.com/nextzlog/zylo@v0.0.0-20210612174204-27dece334bd4

**Comment by jucky154** [comment]
go get : can't request version  "v0.0.0-20210612174204-27dece334bd4" of the main module (github.com/nextzlog/zylo)

**Comment by jucky154** [comment]
ただし、go modに入れるとダウンロードが行われます。

そして、.\asset.go:110:12:undefined : zylo.NewQxSLというのも出てきます

**Comment by jucky154** [comment]
zbuildについては5/27にダウントーどしたものです

**Comment by JG1VPP** [comment]
asset.goは古いものなので削除してください。

**Comment by jucky154** [comment]
削除してもassetからは同じエラーを吐き出します

**Comment by JG1VPP** [comment]
zbuildが古いので、新しいものに取り替えてみてください。

**Comment by jucky154** [comment]
https://github.com/nextzlog/zylo/releases/tag/zbuild (5/6 latest)
をダウンロードしビルドしましたが何も変わりません。
.\asset.go:110:12:undefined : zylo.NewQxSL
と出ます

**Comment by jucky154** [comment]
https://github.com/nextzlog/zylo/blob/master/zutils.go
を見るとNewQxSLという関数などないことが原因かなと思うのですが…

**Comment by jucky154** [comment]
https://github.com/nextzlog/zylo/commit/27dece334bd4e6eeb6b6469cbf26fce7bbd7a86a#diff-de40de7d6f1c2b84b3c57911f9284bfefab53916c207fe8a7f318ab354f2f533L302
にあるようにNewQxSLが LoadQxSLに変わっていることから
asset.goのhttps://github.com/nextzlog/zylo/blob/master/assets/asset.go#L110をLoadQxSLに書き換えたら一応ビルドできました。

**Comment by JG1VPP** [comment]
本件は、最新のzbuildを利用することで解消されます。
今後は、zbuildを新しいバージョンに変えるたびに、
zylo.という接頭辞の付くファイルの内容が変わるので、適宜削除してからzbuildを実行してください。
