### ISSUE TITLE
現在入力中のデータについて

### ISSUE THREAD

**Issue by jucky154** [nextzlog/zylo#4]
https://github.com/jr8ppg/zLog/blob/d3614f8ba7bdd356269e410e0f2772244c399414/zlog/UzLogCW.pas#L71
の以下にあるような $(文字）の現在入力中のコールサイン、rcvdなどを得られる関数が欲しいです。（関数を読んだときだけに得られれば問題ありません）
KHBさんが欲している関数だと思われます。

**Comment by JG1VPP** [comment]
新たに用意したQuery関数を使ってください。
