### ISSUE TITLE
Enrich bundled rules

### ISSUE THREAD

**Issue by JG1VPP** [nextzlog/zylo#7]
Ask JS2FVO to provide the rules including the High School contest, YL contest.

**Comment by jucky154** [comment]
I updated the DLL for the High School contest(https://github.com/jucky154/hscontest ) and confirmed that there was no problem. However main.yml doesn't work. 
![modelnewtype](https://user-images.githubusercontent.com/58735989/131856104-e031659e-a5e5-44d1-adef-6a8f6ce7c52e.png)

**Comment by JG1VPP** [comment]
Could you please try again? I corrected release tags.

**Comment by jucky154** [comment]
Thank you . main.yml worked. (https://github.com/jucky154/hscontest )

**Comment by jucky154** [comment]
https://github.com/jucky154/hscontest/issues/2
